CREATE TABLE IF NOT EXISTS Event (
    id INTEGER IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    A FLOAT(5) NOT NULL,
    B FLOAT(2) NOT NULL,
    C FLOAT(2) NOT NULL,
    type VARCHAR(1) NOT NULL,
    CONSTRAINT chk_type CHECK (type IN ('T', 'F'))
);